### ISSUE TITLE
Pillow error: "cannot identify image file %r" % (filename if filename else fp)

### ISSUE THREAD

**Issue by ROCHatty** [davidbaszucki/py-funcaptcha#1]
Output by program:
````py
Challenge ID: 935ed68e7a103205.9921415701
Session ID: 6185ed68e79813e48.7716929601
# of images: 5
None
None
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\ptvsd_launcher.py", line 119, in <module>
    vspd.debug(filename, port_num, debug_id, debug_options, run_as)
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\debugger.py", line 39, in debug
    run()
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\AaronJ\source\repos\Requests Solver\Requests_Solver.py", line 17, in <module>
    for image, submit in ch.get_iter(ch.image_urls):
  File "C:\Users\AaronJ\source\repos\Requests Solver\py_funcaptcha.py", line 280, in get_iter
    img = Image.open(imgIO)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\PIL\Image.py", line 2862, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x00000186AFE62EE8>
````

My code (just the example code):
```py
from py_funcaptcha import FunCaptchaSession
from PIL import Image

session = FunCaptchaSession(
    public_key="9F35E182-C93C-EBCC-A31D-CF8ED317B996",
    service_url="https://roblox-api.arkoselabs.com",
    page_url="https://www.roblox.com/Login",
    user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36")
ch = session.new_challenge()

print("Challenge ID:", ch.token)
print("Session ID:", ch.session_token)
print("# of images:", len(ch.image_urls))

for image, submit in ch.get_iter(ch.image_urls):
    image.save("latest.png")
    print(submit(40))
```

This happens to the 3th image every time, if you need any more information, just ask

**Comment by ROCHatty** [comment]
I'm guessing it has something to do with the decryption function here: https://github.com/davidbaszucki/py-funcaptcha/blob/master/py_funcaptcha.py#L96

And that's why Pillow can not recognize the image?

**Comment by davidbaszucki** [comment]
The module currently does not detect error messages returned on the image download page.
The error you're experiencing would most likely happen in the following scenarios:
- FC has blocked your IP
- Your internet connection is too slow (requests take >10 seconds, unlikely)

My suggestion is to try doing this via a different IP/proxy.

The following code worked for me:
```python
from py_funcaptcha import FunCaptchaSession

session = FunCaptchaSession(
    public_key="9F35E182-C93C-EBCC-A31D-CF8ED317B996",
    service_url="https://roblox-api.arkoselabs.com",
    page_url="https://www.roblox.com/Login",
    user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36")
ch = session.new_challenge()

print("Challenge ID:", ch.token)
print("Session ID:", ch.session_token)
print("# of images:", len(ch.image_urls))

for image, submit in ch.get_iter():
    image.save("latest.png")
    print(submit(40))
```

**Comment by ROCHatty** [comment]
Hi,
My internet connection isn't slow at all, got a fiber connection, reaching speeds of 600 mb up, 500 mb down.
And my IP isn't blocked as I can still do these Funcaptcha's on Roblox with just 1 image (instead of 5)

**Comment by davidbaszucki** [comment]
Can you try running the code above?

Maybe try adding a time.sleep between each guess in the iterator.

**Comment by ROCHatty** [comment]
I'm using the following:
```py
session = FunCaptchaSession(
    public_key="9F35E182-C93C-EBCC-A31D-CF8ED317B996",
    service_url="https://roblox-api.arkoselabs.com",
    page_url="https://www.roblox.com/Login",
    proxy="https://209.127.127.61:80",
    user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36")
ch = session.new_challenge()

print("Challenge ID:", ch.token)
print("Session ID:", ch.session_token)
print("# of images:", len(ch.image_urls))

count = 0
for image, submit in ch.get_iter():
    count += 1
    image.save("latest.png")

    rot40 = image
    rot40 = rot40.rotate(360-40,expand=False,resample=Image.BICUBIC)
    rot80 = rot40.rotate(360-40,expand=False,resample=Image.BICUBIC)
    rot120 = rot80.rotate(360-40,expand=False,resample=Image.BICUBIC)
    rot160 = rot120.rotate(360-40,expand=False,resample=Image.BICUBIC)
    rot200 = rot160.rotate(360-40,expand=False,resample=Image.BICUBIC)
    rot240 = rot200.rotate(360-40,expand=False,resample=Image.BICUBIC)
    rot280 = rot240.rotate(360-40,expand=False,resample=Image.BICUBIC)
    rot320 = rot280.rotate(360-40,expand=False,resample=Image.BICUBIC)

    rot40.save("latest40.png")
    rot80.save("latest80.png")
    rot120.save("latest120.png")
    rot160.save("latest160.png")
    rot200.save("latest200.png")
    rot240.save("latest240.png")
    rot280.save("latest280.png")
    rot320.save("latest320.png")

    choice = int(input("Number => "))
    pprint.pprint(choice)

    if (choice == 40):
        rot40.save("guess"+str(count)+".png")
        print(submit(40))
    elif (choice == 80):
        rot80.save("guess"+str(count)+".png")
        print(submit(80))
    elif (choice == 120):
        rot120.save("guess"+str(count)+".png")
        print(submit(120))
    elif (choice == 160):
        rot160.save("guess"+str(count)+".png")
        print(submit(160))
    elif (choice == 200):
        rot200.save("guess"+str(count)+".png")
        print(submit(200))
    elif (choice == 240):
        rot240.save("guess"+str(count)+".png")
        print(submit(240))
    elif (choice == 280):
        rot280.save("guess"+str(count)+".png")
        print(submit(280))
    elif (choice == 320):
        rot320.save("guess"+str(count)+".png")
        print(submit(320))
    else:
        print("Could not find match")
        print(submit(0))

    time.sleep(1)

```

Looking at the images (`latest40.png`, `latest80.png`, `latest120.png`, `latest160.png`, `latest200.png`, `latest240.png`, `latest280.png`, `latest320.png`), I'm guessing 40, 80, 120, 160, 200, 240, 280 or 320. Also my guesses get saved. Looking back to my guesses, I'm 100% sure that they are right.

I also tried to submit every guess in minus numbers, which didn't seem to work aswell.

**Comment by davidbaszucki** [comment]
PIL's .rotate method is reversed, therefore you'll have to multiply the choice or .rotate param by *-1
